set(_CATKIN_CURRENT_PACKAGE "pgmappingcooperativo")
set(pgmappingcooperativo_VERSION "0.0.0")
set(pgmappingcooperativo_MAINTAINER "guille <guille@todo.todo>")
set(pgmappingcooperativo_PACKAGE_FORMAT "1")
set(pgmappingcooperativo_BUILD_DEPENDS "geometry_msgs" "image_geometry" "image_transport" "message_generation" "move_base_msgs" "p3dx_description" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_msgs")
set(pgmappingcooperativo_BUILD_EXPORT_DEPENDS "geometry_msgs" "image_geometry" "image_transport" "move_base_msgs" "p3dx_description" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(pgmappingcooperativo_BUILDTOOL_DEPENDS "catkin")
set(pgmappingcooperativo_BUILDTOOL_EXPORT_DEPENDS )
set(pgmappingcooperativo_EXEC_DEPENDS "geometry_msgs" "image_geometry" "image_transport" "move_base_msgs" "p3dx_description" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(pgmappingcooperativo_RUN_DEPENDS "geometry_msgs" "image_geometry" "image_transport" "move_base_msgs" "p3dx_description" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(pgmappingcooperativo_TEST_DEPENDS )
set(pgmappingcooperativo_DOC_DEPENDS )
set(pgmappingcooperativo_URL_WEBSITE "")
set(pgmappingcooperativo_URL_BUGTRACKER "")
set(pgmappingcooperativo_URL_REPOSITORY "")
set(pgmappingcooperativo_DEPRECATED "")