controller_frequency: 10

recovery_behaviors: [{name: rotate_recovery, type: rotate_recovery/RotateRecovery}]

# base_global_planner: "carrot_planner/CarrotPlanner"
# CarrotPlanner:
#   step_size: 10
#   min_dist_from_robot: 10

base_global_planner: "global_planner/GlobalPlanner"
GlobalPlanner:
  allow_unknown: true
  use_dijkstra: false 
  lethal_cost: 50
  neutral_cost: 25
  outline_map: false
  use_grid_path: true 
#   # orientation_window_size: 0
#   old_navfn_behavior: true

# base_global_planner: "navfn/NavfnROS"
# NavfnROS:
#   allow_unknown: true

base_local_planner: "teb_local_planner/TebLocalPlannerROS" 
TebLocalPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.75
  max_vel_y: 0.75
  max_vel_theta: 1.0

  max_vel_x_backwards: 0.75

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  footprint_model/type: "circular"
  footprint_model/radius: 0.2275

  # Obstacle Parameters
  min_obstacle_dist: 0.5
  inflation_dist: 1.5

  # Trajectory Configuration Parameters 
  dt_ref: 0.3
  dt_hysteresis: 0.03
  max_global_plan_lookahead_dist: 10.0
  exact_arc_length: true
  global_plan_viapoint_sep: 2.5

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 360
  xy_goal_tolerance: 0.5
  free_goal_vel: true

  # Optimization Parameters
  weight_kinematics_forward_drive: 999999999999999999999999.0

  # Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning: false

# base_local_planner: "eband_local_planner/EBandPlannerROS" 
# EBandPlannerROS:
#   max_vel_lin: 0.75
#   max_vel_th: 1.0

#   max_vel_x_backwards: 0.75

#   max_acceleration: 0.5
#   max_translational_acceleration: 0.5
#   max_rotational_acceleration: 1.5

#   yaw_goal_tolerance: 360
#   xy_goal_tolerance: 0.5
