track_unknown_space: true
footprint_clearing_enabled: false
always_send_full_costmap: false 
inflation_radius: 0.0 # 0.2275 # (robot radius)

observation_sources: laser_scan

laser_scan:
  data_type: LaserScan

  observation_persistence: 0.0

  marking: true
  # obstacle_range: 5.99

  clearing: true
  # raytrace_range: 5.0
  inf_is_valid: true

