global_costmap:
  update_frequency: 5.0
  publish_frequency: 5.0

  static_map: false 
  rolling_window: false 

  width: 128.0
  height: 128.0

  # resolution: 1

  origin_x: -64.0
  origin_y: -64.0
