global_costmap:
  # global_frame: "/map"
  # robot_base_frame: base_link
  always_send_full_costmap: true
  track_unknown_space: true
  inflation_radius: 0.0
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true 
  rolling_window: false 
  width: 100.0
  height: 100.0
  resolution: 1
